"""Build a PDF report that consolidates project documentation for submission.

It collects: README.md, architecture.md, evaluation_transcript.md, demo_pitch_en.txt, and memory.json summary.
Writes output to docs/assignment_documentation.pdf using reportlab.
"""
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.units import mm

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs"
OUT_DIR.mkdir(exist_ok=True)
OUT_PDF = OUT_DIR / "assignment_documentation.pdf"

SOURCE_FILES = [
    (ROOT / "README.md", "Project README"),
    (ROOT / "architecture.md", "Architecture & Flow"),
    (ROOT / "evaluation_transcript.md", "Evaluation Transcript"),
    (ROOT / "demo_pitch_en.txt", "Demo Pitch (English)")
]

# Add memory.json summary if available
MEM_PATH = ROOT / "memory.json"

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='Heading', fontSize=16, leading=20, spaceAfter=6, alignment=TA_LEFT))
styles.add(ParagraphStyle(name='SubHeading', fontSize=12, leading=14, spaceAfter=4, alignment=TA_LEFT))
styles.add(ParagraphStyle(name='Body', fontSize=10, leading=12))

flow = []

# Title page
flow.append(Paragraph("Voice-first Native Language Service Agent — Documentation", styles['Heading']))
flow.append(Spacer(1, 6))
flow.append(Paragraph("Language: Telugu\nProject: Government Scheme Discovery & Application Agent", styles['Body']))
flow.append(Spacer(1, 12))

for path, title in SOURCE_FILES:
    if not path.exists():
        continue
    flow.append(Paragraph(title, styles['SubHeading']))
    try:
        text = path.read_text(encoding='utf-8')
    except Exception:
        text = path.read_text(encoding='latin-1')

    # Split into paragraphs
    for block in text.split('\n\n'):
        block = block.strip()
        if not block:
            continue
        # short heading detection
        if block.count('\n') == 0 and len(block) < 120 and block.isupper():
            flow.append(Paragraph(block, styles['SubHeading']))
        else:
            # replace markdown headings like # with bold text
            block = block.replace('```bash', '').replace('```', '')
            block = block.replace('#', '')
            # keep it simple
            flow.append(Paragraph(block.replace('\n', '<br/>'), styles['Body']))
        flow.append(Spacer(1, 6))
    flow.append(PageBreak())

# Add memory summary
if MEM_PATH.exists():
    flow.append(Paragraph('Memory Snapshot', styles['SubHeading']))
    mem_txt = MEM_PATH.read_text(encoding='utf-8')
    flow.append(Paragraph(mem_txt.replace('\n', '<br/>'), styles['Body']))
    flow.append(Spacer(1, 6))

# Footer note
flow.append(Paragraph('Generated by project tools. Includes README, architecture, evaluation transcript, and demo pitch.', styles['Body']))

# Build PDF
doc = SimpleDocTemplate(str(OUT_PDF), pagesize=A4,
                        rightMargin=20*mm, leftMargin=20*mm, topMargin=20*mm, bottomMargin=20*mm)

doc.build(flow)
print(f"Wrote PDF: {OUT_PDF}")
